# Introduction

Working with numbers is central to almost all scientific and engineering computations. 
The topic is so important that there are many dedicated libraries to help implement efficient numerical
computations. There are even languages that are specifically designed for numerical computation, such as Fortran
and MATLAB.

NumPy (https://www.numpy.org/) is the most widely used Python library for numerical computations.  It provides an extensive range of data structures and functions for numerical
computation. In this notebook we will explore just some of the functionality.
You will be seeing NumPy in other courses. NumPy can perform many of the operations that you will learn
during the mathematics courses.

Another library, which largely builds on NumPy and provides additional functionality, is SciPy (https://www.scipy.org/). SciPy provides some  more specialised data structures and functions over NumPy. 
If you are familiar with MATLAB, NumPy and SciPy provide much of what is available in MATLAB.

NumPy is a large and extensive library and this activity is just a very brief introduction.
To discover how to perform operations with NumPy, your best resources are the NumPy documentation (https://numpy.org/learn/) and search engines, such as https://stackoverflow.com/.


## Objectives

- Introduction to 1D and 2D arrays (vector and matrices) 
- Manipulating arrays (indexing, slicing, etc)
- Apply elementary numerical operations
- Demonstrate efficiency differences between vectorised and non-vectorised functions

# Importing the NumPy module

To make NumPy available in our programs, we need to import the module. It has become an informal custom to import NumPy using the shortcut '`np`': 

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# Numerical arrays

We have already seen Python 'lists', which hold 'arrays' of data.  We can access the elements of a list using an index because the entries are stored in order. Python lists are very flexible and can hold mixed data types, e.g. combinations of floats and strings, or even lists of lists of lists . . .

The flexibility of Python lists comes at the expense of performance. Many science, engineering and mathematics problems involve very large problems with operations on numbers, and computational speed is important for large problems. To serve this need, we normally use specialised functions and data structures for numerical computation, and in particular for arrays of numbers. Some of the flexibility of lists is traded for performance.

## One-dimensional arrays

A one-dimensional array is a collection of numbers which we can access by index (it preserves order).

### Creating arrays and indexing 

To create a NumPy array of length 10 and initially filled with zeros:

In [3]:
x = np.zeros(10)

print(x)
print(type(x))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


The default type of a NumPy array is `float`. The type can be checked with

In [4]:
print(x.dtype)

float64


You cannot, for example, add a `string` to a `numpy.ndarray`. All entries in the array have the same type.

We can check the length of an array using `len`, which gives the number of entries in the array:

In [5]:
print(len(x))

10


A better way to check the length is to use `x.shape`, which returns a tuple with the dimensions of the array:

In [6]:
print(x.shape)

(10,)


`shape` tells us the size of the array in *each* direction. We will see two-dimensional arrays shortly (matrices), which have a size in each direction.

We can change the entries of an array using indexing,

In [7]:
print(x)

x[0] = 10.0
x[3] = -4.3
x[9] = 1.0

print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[10.   0.   0.  -4.3  0.   0.   0.   0.   0.   1. ]


Remember that indexing starts from zero!

There are other ways to create arrays, such as an array of 'ones':

In [8]:
y = np.ones(5)
print(y)

[1. 1. 1. 1. 1.]


an array of random values:

In [9]:
y = np.random.rand(6)
print(y)

[0.59066157 0.85159665 0.68069375 0.39709057 0.44283974 0.65645683]


or a NumPy array from a Python list:

In [10]:
x = [4.0, 8.0, 9.0, 11.0, -2.0]
y = np.array(x)
print(y)

[ 4.  8.  9. 11. -2.]


Two more methods for creating arrays which we will use in later notebooks are:

- `numpy.arange`; and 
- `numpy.linspace`. 

They are particularly useful for plotting functions.
The function `arange` creates an array with equally spaced values. It is similar in some cases to `range`, which we have seen earlier. To create the array `[0 1 2 3 4 5]` using `arange`:

In [11]:
x = np.arange(6)
print(x)
print(type(x))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


Note that '6' is not included. We can change the start value, e.g.:

In [12]:
x = np.arange(2, 6)
print(x)

[2 3 4 5]


The function `linspace` creates an array with prescribed start and end values (both are included), and a prescribed number on values, all equally spaced:

In [13]:
x = np.linspace(0, 100, 6)
print(x)

[  0.  20.  40.  60.  80. 100.]


The `linspace` function is used extensively for plotting, as we will see in the next notebook.

Don't forget you can use the `help()` function to see the documentation provided for a function, e.g. `help(np.linspace)`.

In [14]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

### Array arithmetic and functions

NumPy arrays support common arithmetic operations, such as addition of two arrays

In [15]:
x = np.array([1.0, 0.2, 1.2])
y = np.array([2.0, 0.1, 2.1])
print(x)
print(y)

# Sum x and y
z = x + y
print(z)

[1.  0.2 1.2]
[2.  0.1 2.1]
[3.  0.3 3.3]


and multiplication of components by a scalar,

In [16]:
z = 10.0*x
print(z)

[10.  2. 12.]


and raising components to a power:

In [17]:
x = np.array([2, 3, 4])
print(x**2)

[ 4  9 16]


We can also apply functions to the components of an array:

In [18]:
# Create an array [0, π/2, π, 3π/2]
x = np.array([0.0, np.pi/2, np.pi, 3*np.pi/2])
print(x)

# Compute sine of each entry
y = np.sin(x)
print(y)

[0.         1.57079633 3.14159265 4.71238898]
[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]


The above has computed the sine of each entry in the array `x`.

Note that the function `np.sin` is used, and not `math.sin` (which was used in previous notebooks). The reason is that `np.sin` is more general -  it can act on lists/arrays of values rather than on just one value. We will apply functions to arrays in the next notebook to plot functions.

We could have computed the sine of each array entry using `for` loops:

In [19]:
y = np.zeros(len(x))
for i in range(len(x)):
    y[i] = np.sin(x[i])

print(y)

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]


but the program becomes longer and harder to read. Additionally, in many cases it will be much slower. 
You might see manipulation of arrays without indexing referred to as 'vectorisation'. When possible, vectorisation is a good thing to do. We compare the performance of indexing versus vectorisation below.

### Performance example: computing the norm of a long vector

Recall that a vector is simply a list of numbers. A geometric interpretation of a vector is that these numbers represent the end point of a directed line root at the origin (e.g. see the column vector interpretation (here)[https://www.bbc.co.uk/bitesize/guides/zgcrjty/revision/1]. The _norm_ of a vector is the distance from the origin to its tip (i.e. its length);

The norm of a vector $x$ is given by: 

$$
\| x \| = \sqrt{\sum_{i=0}^{n-1} x_{i} x_{i}}
$$

where $x_{i}$ is the $i$th entry of $x$. It is the dot product of a vector with itself, 
followed by taking the square root.

To compute the norm, we could loop/iterate over the entries of the vector and sum the square of each entry, and then take the square root of the result.

We will evaluate the norm using two methods for computing the norm of an array of length 10 million to compare their performance. We first create a vector with 10 million random entries, using NumPy:

In [20]:
# Create a NumPy array with 10 million random values
x = np.random.rand(10000000)
print(type(x))

<class 'numpy.ndarray'>


We now time how long it takes to compute the norm of the vector using the NumPy function '`numpy.dot`'. We use the Jupyter 'magic command' [`%time`](Notebook%20tips.ipynb#Simple-timing) to time the operation: 

In [21]:
%time norm = np.sqrt(np.dot(x, x))
print(norm)

CPU times: user 20.5 ms, sys: 5.83 ms, total: 26.3 ms
Wall time: 10.5 ms
1825.739301821867


The time output of interest is '`Wall time`'.

> The details of how `%time` works are not important for this course. We use it as a compact and covenient tool to 
> measure how much time a command takes to execute.

We now perform the same operation with our own function for computing the norm:

In [22]:
def compute_norm(x):
    norm = 0.0
    for xi in x:
        norm += xi*xi
    return np.sqrt(norm)

%time norm = compute_norm(x)
print(norm)

CPU times: user 1.28 s, sys: 0 ns, total: 1.28 s
Wall time: 1.3 s
1825.7393018219911


You should see that the two approaches give the same result, but the 
NumPy function is more than 100 times faster, and possibly more than 100,000 times faster!

The message is that specialised functions and data structures for numerical computations can be many orders of magnitude faster than your own general implementations. On top of that, the specialised functions are much less 
likely to have bugs!

## Two-dimensional arrays

Two-dimensional arrays are very useful for arranging data in many engineering applications and for performing mathematical operations. Commonly, 2D arrays are used to represents matrices. To create the matrix

$$
A = 
\begin{bmatrix} 
2.2 & 3.7 & 9.1\\ 
-4 & 3.1 & 1.3
\end{bmatrix} 
$$

we use:

In [23]:
A = np.array([[2.2, 3.7, 9.1], [-4.0, 3.1, 1.3]])
print(A)

[[ 2.2  3.7  9.1]
 [-4.   3.1  1.3]]


If we check the length of `A`:

In [24]:
print(len(A))

2


it reports the number of rows. To get the shape of the array, we use:

In [25]:
print(A.shape)

(2, 3)


which reports 2 rows and 3 columns (stored using a tuple). To get the number of rows and the number of columns,

In [26]:
num_rows = A.shape[0]
num_cols = A.shape[1]
print("Number of rows is {}, number of columns is {}.".format(num_rows, num_cols))

Number of rows is 2, number of columns is 3.


We can 'index' into a 2D array using two indices, the first for the row index and the second for the column index:

In [27]:
A02 = A[0, 2]
print(A02)

9.1


With `A[1]`, we will get the second row:

In [28]:
print(A[1])

[-4.   3.1  1.3]


We can iterate over the entries of `A` by iterating over the rows, and then the entry in each row:

In [29]:
for row in A:
    print("-----")
    for c in row:
        print(c)

-----
2.2
3.7
9.1
-----
-4.0
3.1
1.3


> **Warning:** NumPy has a `numpy.matrix` data structure. Its use is not recommended as it behaves inconsistently in some cases.

### 2D array (matrix) operations

For those who have seen matrices previously, the operations in this section will be familiar. For those who have not encountered matrices, you might want to revisit this section once matrices have been covered in the mathematics lectures.

#### Matrix-vector and matrix-matrix multiplication

We will consider the matrix $A$:

$$
A  = 
\begin{bmatrix}
3.4 & 2.6 \\
2.1 & 4.5
\end{bmatrix}
$$

and the vector $x$:

$$
x  = 
\begin{bmatrix}
0.2 \\ -1.1
\end{bmatrix}
$$

In [30]:
A = np.array([[3.4, 2.6], [2.1, 4.5]])
print("Matrix A:\n {}".format(A))

x = np.array([0.2, -1.1])
print("Vector x:\n {}".format(x))

Matrix A:
 [[3.4 2.6]
 [2.1 4.5]]
Vector x:
 [ 0.2 -1.1]


We can compute the matrix-vector product $y = Ax$ by:

In [31]:
y = A.dot(x)
print(y)

[-2.18 -4.53]


Matrix-matrix multiplication is performed similarly. Computing $C = AB$, where $A$, $B$, and $C$ are all matrices:

In [32]:
B = np.array([[1.3, 0], [0, 2.0]])

C = A.dot(B)
print(C)

[[4.42 5.2 ]
 [2.73 9.  ]]


The inverse of a matrix ($A^{-1}$) and the determinant ($\det(A)$) can be computed using functions in the NumPy submodule `linalg`:

In [33]:
Ainv = np.linalg.inv(A)
print("Inverse of A:\n {}".format(Ainv))

Adet = np.linalg.det(A)
print("Determinant of A: {}".format(Adet))

Inverse of A:
 [[ 0.45731707 -0.26422764]
 [-0.21341463  0.34552846]]
Determinant of A: 9.839999999999998


> NumPy is large library, so it uses sub-modules to arrange functionality.

A very common matrix is the *identity matrix* $I$. We can create a $4 \times 4$ identity matrix using:

In [34]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array slicing

When working with arrays, it is often useful to extract subsets of an array. We might want just the first 3 entries of a long array, or we might want the second column of a 2D array (matrix). These operations are known as *array slicing* (https://en.wikipedia.org/wiki/Array_slicing).

We will explore slicing through examples. We start by creating an array filled with random values:

In [35]:
x = np.random.rand(5)
print(x)

[0.50224739 0.65123382 0.72443985 0.20560336 0.37628932]


Below are some slicing operations:

In [36]:
# Using ':' implies the whole range of indices, i.e. from 0 -> (length-1)
y = x[:]
print("Slice using '[:]' {}".format(y))

# Using '1:3' implies indices 1 -> 3 (not including 3)
y = x[1:3]
print("Slice using '[1:3]': {}".format(y))

# Using '2:-1' implies indices 2 -> second-from-last
y = x[2:-1]
print("Slice using '[2:-1]': {}".format(y))

# Using '2:-2' implies indices 2 -> third-from-last
y = x[2:-2]
print("Slice using '[2:-2]': {}".format(y))

Slice using '[:]' [0.50224739 0.65123382 0.72443985 0.20560336 0.37628932]
Slice using '[1:3]': [0.65123382 0.72443985]
Slice using '[2:-1]': [0.72443985 0.20560336]
Slice using '[2:-2]': [0.72443985]


> Note the use of the index `-1`. The index `-1` corresponds to the last entry in the array, and `-2` the 
> second last entry, etc. This is convenient if we know how far in from the end of an array a desired entry is.
> By using negative indices we can express this without reference to the length of the array.

If we want a slice to run from the start of an array, or to the end of an array, we do: 

In [37]:
# Using ':3' implies start -> 3 (not including 3)
y = x[:3]
print("Slice using '[:3]': {}".format(y))

# Using '4:' implies 4 -> end
y = x[4:]
print("Slice using '[4:]': {}".format(y))

# Using ':' implies start -> end
y = x[:]
print("Slice using '[:]': {}".format(y))

Slice using '[:3]': [0.50224739 0.65123382 0.72443985]
Slice using '[4:]': [0.37628932]
Slice using '[:]': [0.50224739 0.65123382 0.72443985 0.20560336 0.37628932]


Slicing can be applied to 2D arrays:

In [38]:
B = np.array([[1.3, 0], [0, 2.0]])
print(B)

# Extract second row
r = B[1, :]
print(r)

[[1.3 0. ]
 [0.  2. ]]
[0. 2.]


There is more to array slicing syntax, for example it is possible to extract every 3rd entry. If you need to extract a sub-array, check first if you can do it using the compact array slicing syntax.

## Exercise 07.1 (indexing and timing)

Create two very long NumPy arrays `x` and `y` and sum the arrays using:

1. The NumPy addition syntax, `z = x + y`; and
2. A `for` loop that computes the sum entry-by-entry

Compare the time required for the two approaches for vectors of different lengths (use a very long vector for 
the timing). The values of the array entries are not important for this test. Use `%time` to report the time.

*Hint:* To loop over an array using indices, try a construction like:

In [39]:
import numpy as np

In [40]:
x = np.ones(10)
y = np.ones(len(x))
for i in range(len(x)):
    print(x[i]*y[i])

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


#### (1) Add two vectors using built-in addition operator:

In [41]:
#create two long arrays of random number
x = np.random.rand(1000000)
y = np.random.rand(1000000)

#time how long it takes to add them by bult-in addition operator
%time z = x + y

CPU times: user 0 ns, sys: 3.59 ms, total: 3.59 ms
Wall time: 3.6 ms


#### (2) Add two vectors using own implementation:

In [44]:
#create function to add two arrays index by index
def addition(x, y):
    """Creates new array of the addition of two other arrays"""
    
    z = np.zeros(len(x))
    
    for i in range(len(x)):
        z[i] = x[i] + y[i]
    
    return z

%time addition(x,y)
    

CPU times: user 269 ms, sys: 0 ns, total: 269 ms
Wall time: 267 ms


array([1.19888736, 1.02758774, 1.74255573, ..., 0.4323914 , 0.70484745,
       0.73132611])

## Exercise 07.2 (member functions and slicing)

Anonymised scores (out of 60) for an examination are stored in a NumPy array. Write:

1. A function that takes a NumPy array of the raw scores and returns the scores as percentages, sorted from 
   lowest to highest (try using `scores.sort()`, where `scores` is a NumPy array holding the scores).
1. A function that returns the maximum, minimum and mean of the raw scores as a dictionary with the 
   keys '`min`', '`max`' and '`mean`'. Use the NumPy array functions `min()`, `max()` and `mean()` to do the 
   computation, e.g. `max = scores.max()`.  
   
   Design your function for the min, max and mean to optionally exclude the highest and lowest scores from the 
   computation of the min, max and mean. 
   
   *Hint:* sort the array of scores and use array slicing to exclude
   the first and the last entries.

Use the scores 
```python
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
```
to test your functions.

In [57]:
#create functions
def to_percentage_and_sort(scores):
    """returns percentage score, sorted from low to high"""
    
    #order scores from lowest to highest
    scores.sort()
    
    #calculate score percentage
    scores_percent = scores/60 * 100
    
    return scores_percent


def statistics(scores, exclude=False):
    """create dictionary of min, max, mean scores"""
    
    #order scores from low to highest
    scores.sort()
    
    #optionally exclude highest and lowest values when exculde == True  
    if exclude:
        
        #remove highest and lowest values.
        scores = scores[1:-1]
        
    #calculate min, max and mean
    min_score = scores.min()
    max_score = scores.max()
    mean_score = scores.mean()
    
    #create dictionary to store min, max and mean values
    score_stats = {"min" : min_score,
                   "max" : max_score,
                   "mean": mean_score}
    
    return score_stats

    
    
#test functions
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])

scores_percent = to_percentage_and_sort(scores)
scores_stats = statistics(scores)

print(scores_percent)
print(scores_stats)

[13.         40.         58.33333333 70.         96.66666667]
{'min': 7.8, 'max': 58.0, 'mean': 33.36}


In [58]:
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
assert np.isclose(to_percentage_and_sort(scores), [ 13.0, 40.0, 58.33333333,  70.0, 96.66666667]).all()

s0 = statistics(scores)
assert round(s0["min"] - 7.8, 10) == 0.0
assert round(s0["mean"] - 33.36, 10) == 0.0
assert round(s0["max"] - 58.0, 10) == 0.0

s1 = statistics(scores, True)
assert round(s1["min"] - 24.0, 10) == 0.0
assert round(s1["mean"] - 33.666666666666666667, 10) == 0.0
assert round(s1["max"] - 42.0, 10) == 0.0

## Exercise 07.3 (slicing)

For the two-dimensional array

In [62]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
print(A)

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]


use array slicing for the below operations, printing the results to the screen to check. Try to use array slicing such that your code would still work if the dimensions of `A` were enlarged.



#### 1. Extract the third column as a 1D array

In [63]:
# YOUR CODE HERE
print(A[:, 2])

[  -2.43   54.7     3.64 -113.2 ]


#### 2. Extract the first two rows as a 2D sub-array

In [65]:
# YOUR CODE HERE
print(A[0:2, :])

[[ 4.    7.   -2.43 67.1 ]
 [-4.   64.   54.7  -3.33]]


#### 3.  Extract the bottom-right $2 \times 2$ block as a 2D sub-array

In [67]:
# YOUR CODE HERE
print(A[2:4, 2:])

[[   3.64    4.11]
 [-113.2   323.22]]


#### 4. Sum the last column

In [68]:
# YOUR CODE HERE
print(A[:, -1].sum())

391.1


In [ ]:
from scipy import optimize

#NOT RELEVENT